### ISSUE TITLE
[Bug - Mac Release on M1 and Windows] Distributable not able to run on main (9/11/2023)

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#354]
Original comment chain starting at https://github.com/NeurodataWithoutBorders/nwb-guide/pull/337#issuecomment-1711919404

Just reproduced it on the DANDI Hub, the one shared computing environment we all have access to; I suggest we start there and see if fixing that fixes the other platforms

I also wasn't able to run dev mode either on the Hub - I'm pretty sure both used to work, up to those previous backend distribution issues, right?

To be clear, workflow is

1) fresh clone of `nwb-guide`
2a) `npm start` to ensure dev mode is working
2b) might need to do `npm ci` if `npm start` doesn't work due to 'electron-vite' not being found
3) `npm run build:<platform>`
4a) Windows: run setup `.exe`, follow instructions, then try to run application from the installed location
4b) Mac: `.dmg` to App folder, try to run from there
4c) Linux: Configure `.AppImage` to run as executable, then try to run it (on the Hub, do so from the remote desktop)

Might be related to issues seen by @alessandratrapani on ubuntu?

**Comment by CodyCBakerPhD** [comment]
I wouldn't proceed  with many more dev features (including interfaces) until this is resolved since it makes the initial setup process harder for alpha testers

**Comment by rly** [comment]
On M1 Mac, on **main**, creating a clean M1 Mac environment does not even solve for me using conda or mamba. I'm not sure how that came to be (surely it worked at one point??), and why @CodyCBakerPhD could create an env but not me.

In any case, if I create a clean M1 Mac environment using the `debug_mac_dist` branch where the reqs are fixed, on a clean clone of the repo, because of the sonpy error #89 that prohibits M1 Mac installs, I need to first run `pip uninstall sonpy --yes` before running `npm run build:mac`. Then I can double-click `dist/NWB GUIDE-0.0.4-arm64.dmg`, drag the NWB GUIDE icon to Applications, and double click the new app. Everything runs smoothly there as far as I can tell. I went through the tutorial up until dandi upload.

**Comment by CodyCBakerPhD** [comment]
Now that I think about it, did we ever get the full app to work on the Hub? Last time we hit the wall was on the Flask not even building, so does anyone remember being able to run it there successfully?

I still get the same errors, but they are related to GPU aspects (even on the GPU instance) so IDK. Manually navigating to the local host shows the front-end displaying something, but it says the backend isn't running

**Comment by CodyCBakerPhD** [comment]
> I confirmed that I was able to get the M1 dist working on @rly's branch 

However, when I use the CI to successfully deploy from the `more_debugs_m1` branch (https://github.com/NeurodataWithoutBorders/nwb-guide/actions/runs/6163257564)

If I download the `.dmg` from the latest release (deployed from the debugged dev branch): https://github.com/NeurodataWithoutBorders/nwb-guide/releases/tag/v0.0.4

then, once I bypass the security things due to the lingering signing issue #309, the app immediately crashes upon launch - I get a brief glimpse of the splash screen, which is more than I get on Windows

 This goes back to the question of if we will need manual deployments for M1 specific distributions. @rly When you get a chance, and while you're solving the #309 problem, could you try manually signing and deploying a M1 release from your machine using those debugged dev branches?

**Comment by CodyCBakerPhD** [comment]
After a fresh wipe of everything on Windows, the recursion depth issue is not present, at least when running on `main`

Electron issue ticket https://github.com/electron/electron/issues/21503 is exactly what I see; tried all solutions

i) cleared various AppData folders
ii) tried `npm config set ignore-scripts` with both `true` and `false` with fresh `npm install` - even made sure to clear `node_modules` before reinstalling (I notice the deployment CI's all use this flag?)
iii) `npm install electron@13.6.9 --save-dev` (we already seem to use that version, but the flag is new I think)

None of them have worked on Windows so far. Still fails to even display the splash screen; processes remain running in the background but nothing gets rendered/launched
